version: '3'
services:
  web:
    container_name: laravel-web-apache
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    # volumes:
    #   - ./path/to/your/database.sql:/docker-entrypoint-initdb.d/database.sql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "9999:80"
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - mariadb